version: '3.8'

services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  init-topics:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      sleep 5
      echo -e 'Creating kafka topics'
      /usr/bin/kafka-topics --create --topic note.created --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      /usr/bin/kafka-topics --create --topic note.deleted --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      echo -e 'Successfully created the following topics:'
      /usr/bin/kafka-topics --bootstrap-server kafka:9092 --list
      "      
  alembic_migration:
    build:
      context: .
    environment:
      ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
    command: >
      sh -c "alembic upgrade head"
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy


  notes-app:
    build:
      context: .
    depends_on:
      kafka:
        condition: service_healthy
      alembic_migration:
        condition: service_completed_successfully
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
      AUTH_JWT_SECRET_KEY: ${AUTH_JWT_SECRET_KEY}
      AUTH_JWT_ALGORITHM: ${AUTH_JWT_ALGORITHM}
      AUTH_ACCESS_TOKEN_EXPIRE_MINUTES: ${AUTH_ACCESS_TOKEN_EXPIRE_MINUTES}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      UVICORN_FASTAPI_HOST: ${UVICORN_FASTAPI_HOST}
      UVICORN_FASTAPI_PORT: ${UVICORN_FASTAPI_PORT}
    command: >
      sh -c "uv run notes_app"
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data

  celery_worker:
    build:
      context: .
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
      AUTH_JWT_SECRET_KEY: ${AUTH_JWT_SECRET_KEY}
      AUTH_JWT_ALGORITHM: ${AUTH_JWT_ALGORITHM}
      AUTH_ACCESS_TOKEN_EXPIRE_MINUTES: ${AUTH_ACCESS_TOKEN_EXPIRE_MINUTES}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      UVICORN_FASTAPI_HOST: ${UVICORN_FASTAPI_HOST}
      UVICORN_FASTAPI_PORT: ${UVICORN_FASTAPI_PORT}
    command: celery -A notes_app.infrastructure.celery.celery_app worker --loglevel=info
    depends_on:
      redis:
        condition: service_started
      alembic_migration:
        condition: service_completed_successfully

  celery_beat:
    build:
      context: .
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
      SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
      AUTH_JWT_SECRET_KEY: ${AUTH_JWT_SECRET_KEY}
      AUTH_JWT_ALGORITHM: ${AUTH_JWT_ALGORITHM}
      AUTH_ACCESS_TOKEN_EXPIRE_MINUTES: ${AUTH_ACCESS_TOKEN_EXPIRE_MINUTES}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      UVICORN_FASTAPI_HOST: ${UVICORN_FASTAPI_HOST}
      UVICORN_FASTAPI_PORT: ${UVICORN_FASTAPI_PORT}
    command: celery -A notes_app.infrastructure.celery.celery_app beat --loglevel=info
    depends_on:
      redis:
        condition: service_started
      alembic_migration:
        condition: service_completed_successfully

volumes:
  postgres_data:
  redis_data: